#!/usr/bin/env sh

main() {
  rm -rf ~/.cache/wal/
  rm -rf ~/.config/wpg/schemes/*

  cpwrconf

  BACKGROUNDS=$(ls ~/.config/background/ | cut -d ' ' -f 1)
  NUMBERS_OF_BACKGROUNDS=0;

  for j in ${BACKGROUNDS}; do
    ((NUMBERS_OF_BACKGROUNDS++));
  done;

  WALPAPER=$(
    echo ${BACKGROUNDS} | cut -d ' ' -f $((1 + RANDOM % NUMBERS_OF_BACKGROUNDS))
  )

  ln -s ~/.config/background/${WALPAPER} ~/.config/background-noblur.png

  convert \
    ~/.config/background/${WALPAPER} \
    -filter Gaussian -blur 0x32 \
    ~/.config/background.png &

  wpg -a ~/.config/background/${WALPAPER}
  wpg -A ${WALPAPER}
  wpg -s ${WALPAPER}
  source ~/.cache/wal/colors.sh

  # Replace color with #
  FILES=(
    ~/.config/rofi/applets/type-5/style-3.rasi
    ~/.config/rofi/themes/shared/colors.rasi
  )

  for FILE in ${FILES[@]}; do
    sed -i \
      -e "s/{{ background }}/${background}/g" \
      -e "s/{{ foreground }}/${foreground}/g" \
      -e "s/{{ color0 }}/${color0}/g" \
      -e "s/{{ color1 }}/${color2}/g" \
      -e "s/{{ color2 }}/${color1}/g" \
      -e "s/{{ color3 }}/${color3}/g" \
      -e "s/{{ color4 }}/${color4}/g" \
      -e "s/{{ color8 }}/${color8}/g" \
      -e "s/{{ color15 }}/${color15}/g" ${FILE} &
  done

  pkill -f swaybg &
  pkill -f waybar &

  wait

  swaybg -m fill -i ~/.config/background/${WALPAPER} &
  hyprctl reload &
  waybar &
  cp ~/.cache/wal/colors-kitty.conf ~/.config/kitty/colors-kitty.conf &
}

main > /dev/null 2>&1
