#!/usr/bin/env sh

remove_old() {
  cpwrconf &
}

get_walpaper() {
  BACKGROUNDS=$(ls ~/.config/background/ | cut -d ' ' -f 1)
  NUMBERS_OF_BACKGROUNDS=0;

  for j in ${BACKGROUNDS}; do
    ((NUMBERS_OF_BACKGROUNDS++));
  done;

  WALPAPER=$(
    echo ${BACKGROUNDS} | cut -d ' ' -f $((1 + RANDOM % NUMBERS_OF_BACKGROUNDS))
  )
}

make_blur() {
  ln -s ~/.config/background/${WALPAPER} ~/.config/background-noblur.png &

  convert \
    ~/.config/background/${WALPAPER} \
    -filter Gaussian -blur 0x32 \
    ~/.config/background.png &
}

update_wal() {
  wpg -a ~/.config/background/${WALPAPER}
  wpg -A ${WALPAPER}
  wpg -s ${WALPAPER}
}

restart_all() {
  pkill -f swaybg &
  pkill -f waybar &

  wait

  swaybg -m fill -i ~/.config/background/${WALPAPER} &
  hyprctl reload &
  waybar &
}

main() {
  remove_old
  get_walpaper
  make_blur
  update_wal

  wait

  restart_all
}

main > /dev/null 2>&1
